apiVersion: v1
kind: Secret
metadata:
  name: {{ include "botgastospareja.fullname" . }}-secrets
  labels:
    {{- include "botgastospareja.labels" . | nindent 4 }}
type: Opaque
data:
  telegram-bot-token: {{ .Values.secrets.telegramBotToken | b64enc }}

